### PR TITLE
fix coverage image url

### PR DESCRIPTION
**Pull request by dshafer**

### CODE REVIEW

**Comment by dshafer** [comment]
This change was needed for this plugin to work with my company's GitHub enterprise server - not sure if you want to bring it back into the main repo

**Comment by terma** [comment]
Could you please be more specific what the problem did you have? GitHub not able to correctly render markdown to html?

**Comment by dshafer** [comment]
Actually I think the issue is with our jenkins server (Cloudbees jenkins 1.6.something).  My problem is that prior to this change, the `/coverage-status-icon` endpoint returns an empty response instead of the expected svg resource.  I eventually diagnosed it with curl:

```
$> curl https://jenkins.mydomain.com/coverage-status-icon?coverage=80.0\&masterCoverage=50.0
[ empty document returned ]
$> curl https://jenkins.mydomain.com/coverage-status-icon/?coverage=80.0\&masterCoverage=50.0
<svg xmlns="http://www.w3.org/2000/svg" height="20" width="255">
    <linearGradient id="a" x2="0" y2="100%">
        <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
        <stop offset="1" stop-opacity=".1"/>
    </linearGradient>
[----  SNIP SNIP SNIP ----]
</svg>
```

I don't know enough about jenkins to say whether this is a safe change; I mainly wanted to bring it to your attention that I had to make this change for my environment.  Perhaps this should be an option in the plugin's global preferences?

**Comment by terma** [comment]
Ok. I think I need to fix that. As plugin moved to Jenkins repo I've created issue https://issues.jenkins-ci.org/browse/JENKINS-38477

**Comment by terma** [comment]
Fixed in version 1.0.9. As plugin in Jenkins Repo you can find new version in on Jenkins Admin console or download from https://wiki.jenkins-ci.org/display/JENKINS/GitHub+PR+Coverage+Status+Plugin

**Pull request closed without merging**
